# Generated by Django 2.2.24 on 2022-11-20 14:57

from django.db import migrations


def fill_owners_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all().iterator():
        for flat in Flat.objects.filter(owner=owner.name, owners_phonenumber=owner.phone_number).iterator():
            owner.flats.add(flat)
        print(f'{owner.id} complete')


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20221120_1756'),
    ]

    operations = [
        migrations.RunPython(fill_owners_flats)
    ]
