# Generated by Django 2.2.24 on 2022-11-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20221120_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Flat',
            name='owner',
        ),

        migrations.RemoveField(
            model_name='Flat',
            name='owners_phonenumber',
        ),

        migrations.RemoveField(
            model_name='Flat',
            name='owner_pure_phone',
        ),
    ]
